language: go
sudo: false
go:
  - "1.11"
  - "1.12"
  - "1.13"
  - tip
os:
  - linux
  - osx
script:
  - GO111MODULE=on make test
branches:
  only:
    - master
after_success:
  - make cross
  - ghr --username b4b4r07 --token $GITHUB_TOKEN --replace $(make version) dist/
